apiVersion: v1
kind: Service
metadata:
  name: kubernetes-database-service
spec:
  selector:
    app: kubernetes-database
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP