version: '3.4'

services:
  api:
    build: ./Kubernetes
    ports:
      - 5000:5000
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    ports: 
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Password123
